version: '3'
services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_USER: nus
      MYSQL_PASSWORD: RaNdOMSt0nGP@assW0rd
      MYSQL_DATABASE: kasper
    volumes:
      - ./dockerdb/mount:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
